### ISSUE TITLE
Project relies on non-existent development dependency

### ISSUE THREAD

**Issue by nirvdrum** [envygeeks/pathutil#3]
The Gemfile lists `luna-rubocop-formatters` as a development dependency, but this gem was deleted by its author. As a result, it's not possible to clone this project and start development on it. As a secondary effect, I think there's a potential security risk here as the `luna-rubocop-formatters` name will soon become available to anyone on RubyGems and at that point this project will attempt to bundle install code from a potentially untrusted 3rd party.

**Comment by envygeeks** [comment]
Hey @nirvdrum, this project was slated to get fixed in a few weeks, but since you filed a ticket I'll get it fixed  here in the next hour, so that you can continue to use it and develop on it if you like.

Thanks!
